/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/common/ui/button/Button.vue')['default']
    CategoryNav: typeof import('./../components/home/CategoryNav.vue')['default']
    EventCard: typeof import('./../components/home/EventCard.vue')['default']
    EventSection: typeof import('./../components/home/EventSection.vue')['default']
    HomeBanner: typeof import('./../components/home/HomeBanner.vue')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideChevronLeft: typeof import('~icons/lucide/chevron-left')['default']
    IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    IconLucideMapPin: typeof import('~icons/lucide/map-pin')['default']
    IconLucideSearch: typeof import('~icons/lucide/search')['default']
    IconLucideSmartphone: typeof import('~icons/lucide/smartphone')['default']
    IconLucideTicket: typeof import('~icons/lucide/ticket')['default']
    IconLucideUser: typeof import('~icons/lucide/user')['default']
    Input: typeof import('./../components/common/ui/input/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./../components/common/TheHeader.vue')['default']
  }
}
